.io-config.json
ionic.config.json
package.json
src/app/app.module.ts

Use `ionic upload` to upload the app and make it accessible on ionic view.
Close #7

Set up app on ionic.io

---

contributing.json

Disable imperative title in issues

---

src/app/app.module.ts
src/mocks.ts
src/pages/add-item/add-item.html
src/pages/add-item/add-item.spec.ts
src/pages/add-item/add-item.ts
src/pages/home/home.html
src/pages/home/home.scss
src/pages/home/home.spec.ts
src/pages/home/home.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts
src/test.ts

Add visual elements of the home screen and the add-item screen
Close #34

Add add item screen

---

package.json
src/app/app.module.ts
src/mocks.ts
src/pages/login/login.html
src/pages/login/login.scss
src/pages/login/login.spec.ts
src/pages/login/login.ts
src/providers/user-data.spec.ts
src/providers/user-data.ts
src/test.ts

Add visuals elements of the login screen.
Close #33

Add login screen

---

README.md

Close #38
I did not include the logo, because it did not fit well in the readme.

Improve readme visuals

---

src/app/app.module.ts

Hide tabs on child nav

---

src/mocks.ts
src/pages/home/home.spec.ts
src/pages/rental/rental.html
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts

Add return screen

---

package.json

Update ionic to 2.0.1

---

src/app/app.component.ts
src/app/app.module.ts
src/app/app.spec.ts
src/mocks.ts
src/pages/home/home.spec.ts
src/pages/home/home.ts
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts
src/pages/item/item.spec.ts
src/pages/item/item.ts
src/pages/login/login.spec.ts
src/pages/login/login.ts
src/pages/rental-details/rental-details.spec.ts
src/pages/rental-details/rental-details.ts
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/pages/tabs/tabs.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts
src/providers/stockpile-data.spec.ts
src/providers/user-data.spec.ts
src/providers/user-data.ts
src/test-data.ts
src/test.ts

Closes #56 
Made the code more consistent, moved static values to `src/test-data.ts` and fixed a few typos and errors.

Improve code

---

config.xml
src/pages/home/home.html
src/pages/home/home.spec.ts
src/pages/home/home.ts
src/pages/rental/rental.html
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/test.ts

Closes #51 
Test coverage decreased because I was not able to unit test the Barcode Scanner since it's a Cordova plugin.
There is also some duplication of code since the scanner is present in two components. Not sure it is worth to make a service only for that though.
For the html duplication, I created an issue: #70

Add scanner

---

src/constants.ts
src/mocks.ts
src/pages/item/item.html
src/pages/item/item.spec.ts
src/pages/item/item.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts
src/providers/user-data.ts
src/test-data.ts

Add item to inventory

---

src/pages/item/item.html
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts

Add delete item call to api

---

src/constants.ts
src/pages/rental-details/rental-details.html
src/pages/rental-details/rental-details.spec.ts
src/pages/rental-details/rental-details.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts
src/test-data.ts

Check an item out to the organization

---

config.xml
src/pages/login/login.html

Closes #73
Changed email validation regex to a more standard and permissive one.

Fix email validation regex

---

src/constants.ts
src/pages/item/item.html
src/pages/item/item.spec.ts
src/pages/item/item.ts
src/providers/inventory-data.ts
src/test-data.ts

Get item properties from api

---

config.xml
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts

Return items

---

src/constants.ts
src/mocks.ts
src/pages/home/home.ts
src/pages/item/item.spec.ts
src/pages/item/item.ts
src/pages/login/login.spec.ts
src/pages/login/login.ts
src/pages/rental-details/rental-details.spec.ts
src/pages/rental-details/rental-details.ts
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/providers/inventory-data.ts
src/providers/stockpile-data.ts
src/test-data.ts
src/test.ts

Add toast notifications

---

src/mocks.ts
src/pages/item/item.html
src/pages/item/item.spec.ts
src/pages/item/item.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts
src/test-data.ts

Remove status field

---

src/providers/inventory-data.ts

Move api calls in private method for abstraction

---

src/constants.ts
src/mocks.ts
src/pages/inventory/inventory.html
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts
src/pages/item/item.spec.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts
src/test-data.ts

Closes #53
We will have to talk with our client about how they would use the view inventory page before implementing more options/filtering.

Add screen to view inventory

---

src/constants.ts
src/mocks.ts
src/pages/home/home.spec.ts
src/pages/home/home.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts
src/test-data.ts
src/test.ts

Check item status before renting/returning

---

.travis.yml
src/pages/item/item.html
src/pages/item/item.spec.ts
src/pages/item/item.ts
src/providers/inventory-data.ts
src/test-data.ts

Link brands and models

---

src/pages/item/item.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts

Add call to api for item properties

---

src/providers/stockpile-data.spec.ts
src/providers/stockpile-data.ts

Investigate toast

---

src/mocks.ts
src/pages/home/home.spec.ts
src/pages/home/home.ts
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/providers/stockpile-data.ts
src/test-data.ts

Move barcode scanning to stockpile-data

---

src/constants.ts
src/pages/home/home.spec.ts
src/pages/home/home.ts
src/pages/inventory/inventory.html
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts
src/test-data.ts

Add inventory filtering

---

src/pages/home/home.html
src/pages/home/home.spec.ts
src/pages/home/home.ts
src/pages/inventory/inventory.html
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts

Mode add and edit item options to inventory view

---

src/pages/home/home.spec.ts
src/pages/home/home.ts
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts
src/pages/item/item.spec.ts
src/pages/item/item.ts
src/pages/login/login.ts
src/pages/rental-details/rental-details.spec.ts
src/pages/rental-details/rental-details.ts
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts
src/providers/user-data.spec.ts
src/providers/user-data.ts
src/test-data.ts

Closes #122 
Errors from the api were not displayed because they weren't parsed to JSON.

Fix error handling

---

src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts
src/pages/item/item.html
src/pages/item/item.spec.ts
src/pages/item/item.ts
src/providers/inventory-data.spec.ts
src/test-data.ts

Remove brandID from PUT item requests

---

src/pages/tabs/tabs.html

Closes #103.
Could not think of a better name for the Scan tab.

103/Change View tab to Inventory

---

src/pages/item/item.html

Fix click event in field in item

---

src/app/app.module.ts
src/pages/inventory/inventory.html
src/pages/item-filter/item-filter.html
src/pages/item/item.html
src/pages/login/login.html
src/pages/rental-details/rental-details.html
src/pages/rental/rental.html
src/pages/tabs/tabs.html
src/providers/stockpile-data.ts
src/theme/variables.scss

Improve look and feel of the app

---

src/mocks.ts
src/pages/home/home.spec.ts
src/pages/home/home.ts
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/test-data.ts

Make cancelling scanner to return to previous page

---

src/constants.ts
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/test-data.ts

Check for item status inside rental

---

src/mocks.ts
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts
src/pages/item/item.spec.ts
src/pages/item/item.ts
src/pages/rental/rental.ts
src/test.ts

Closes #140
Also updated `item.ts` to publish an event when an item is updated or created and `rental.ts` to subscribe to this event and update the item in the list of items that are about to be rented/returned.

Reload inventory page after editing item

---

src/pages/item-filter/item-filter.spec.ts
src/providers/inventory-data.spec.ts
src/providers/stockpile-data.spec.ts
src/providers/user-data.spec.ts

Improve test syntax

---

src/pages/item-filter/item-filter.spec.ts
src/pages/rental/rental.spec.ts
src/providers/stockpile-data.spec.ts
src/test-data.ts

Improve test coverage

---

LICENSE

Add open source license

---

package.json
src/app/app.component.ts
src/app/app.module.ts
src/app/app.spec.ts
src/mocks.ts
src/providers/user-data.spec.ts
src/providers/user-data.ts
src/services/auth-http.ts
src/services/raven-error-handler.ts

Closes #149 
Will eventually be able to link Sentry to app versions and source code files map so that we can see where the error happened in the code in Sentry.

Send errors to external service

---

src/pages/rental-details/rental-details.ts

Fix error when item is rented

---

src/pages/rental/rental.html
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/test-data.ts

Remove scanned item from rent screen

---

src/pages/rental-details/rental-details.html

Remove start dates

---

src/pages/home/home.spec.ts
src/pages/home/home.ts
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts

Fix double request on rental

---

src/app/app.module.ts
src/pages/inventory-filter/inventory-filter.html
src/pages/inventory-filter/inventory-filter.spec.ts
src/pages/inventory-filter/inventory-filter.ts
src/pages/inventory/inventory.html
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts
src/theme/variables.scss

Closes #171
I actually moved filters to an option in the toolbar. It is much cleaner and reduces the number of choices the user can make when looking at the page. We'll have to make sure the process to choose filters is intuitive though.
Here's how it looks now:

Add ability to hide filters

---

src/app/app.module.ts
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts
src/pages/item/item.spec.ts
src/pages/item/item.ts
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/pages/view-item/view-item.html
src/pages/view-item/view-item.spec.ts
src/pages/view-item/view-item.ts
src/providers/inventory-data.spec.ts

Closes #90 
Created new page to view items with the option of editing.

Add page to view items

---

src/app/app.component.ts
src/app/app.html
src/app/app.spec.ts
src/constants.ts
src/mocks.ts
src/pages/login/login.ts
src/providers/user-data.spec.ts
src/providers/user-data.ts
src/test-data.ts

Add ability view user info

---

.io-config.json
ionic.config.json

Update ionic ID

---

.angular-cli.json

Remove services from test coverage

---

src/app/app.component.ts
src/app/app.html
src/app/app.module.ts
src/app/app.spec.ts
src/constants.ts
src/mocks.ts
src/pages/edit-account/edit-account.html
src/pages/edit-account/edit-account.spec.ts
src/pages/edit-account/edit-account.ts
src/pages/login/login.ts
src/providers/user-data.spec.ts
src/providers/user-data.ts
src/test-data.ts

Allow users to edit their account info

---

src/constants.ts

Remove exclamation points from messages

---

src/app/app.component.ts
src/app/app.html
src/app/app.module.ts
src/app/app.spec.ts
src/constants.ts
src/mocks.ts
src/pages/change-password/change-password.html
src/pages/change-password/change-password.spec.ts
src/pages/change-password/change-password.ts
src/pages/edit-account/edit-account.html
src/pages/edit-account/edit-account.ts
src/pages/edit-item/edit-item.html
src/pages/login/login.html
src/pages/rental-details/rental-details.html
src/pages/view-account/view-account.html
src/pages/view-account/view-account.spec.ts
src/pages/view-account/view-account.ts
src/pages/view-item/view-item.html
src/providers/user-data.spec.ts
src/providers/user-data.ts
src/test-data.ts

Add ability to change password

---

src/constants.ts
src/pages/view-account/view-account.html
src/pages/view-account/view-account.spec.ts
src/pages/view-account/view-account.ts
src/providers/user-data.spec.ts
src/providers/user-data.ts

Add ability to delete users

---

src/constants.ts
src/pages/inventory/inventory.html
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts

Add infinite scroll in inventory

---

src/mocks.ts
src/pages/edit-item/edit-item.spec.ts
src/pages/edit-item/edit-item.ts
src/pages/edit-kit/edit-kit.ts
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/pages/view-item/view-item.spec.ts
src/pages/view-item/view-item.ts

Fix nav pop after delete

---

src/pages/view-kit/view-kit.spec.ts
src/pages/view-kit/view-kit.ts

Fix going back while editing kit

---

src/constants.ts

Remove extra space in messages

---

src/pages/add-kit-item/add-kit-item.spec.ts
src/pages/add-kit-item/add-kit-item.ts
src/pages/edit-item/edit-item.ts
src/pages/edit-kit/edit-kit.spec.ts
src/pages/edit-kit/edit-kit.ts

Access constants through static object

---

src/pages/edit-item/edit-item.ts

Fix item creation with empty barcode

---

src/app/app.component.ts
src/pages/add-kit-item/add-kit-item.ts
src/pages/change-password/change-password.ts
src/pages/edit-account/edit-account.ts
src/pages/edit-item/edit-item.ts
src/pages/edit-kit/edit-kit.ts
src/pages/home/home.ts
src/pages/inventory-filter/inventory-filter.ts
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts
src/pages/item-filter/item-filter.ts
src/pages/kits/kits.ts
src/pages/login/login.ts
src/pages/rental-details/rental-details.ts
src/pages/rental/rental.ts
src/pages/tabs/tabs.ts
src/pages/view-account/view-account.ts
src/pages/view-item/view-item.ts
src/pages/view-kit/view-kit.ts
src/providers/user-data.ts
src/services/auth-http-helpers.ts
src/services/raven-error-handler.ts

Add descriptive comments to functions

---

src/pages/view-kit/view-kit.spec.ts
src/pages/view-kit/view-kit.ts
src/test-data.ts

Change kit name in view kit

---

src/pages/inventory/inventory.html
src/pages/kits/kits.html

Prompt user for action if no item in inventory

---

src/app/app.scss
src/constants.ts
src/mocks.ts
src/pages/inventory/inventory.html
src/pages/kits/kits.html
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/providers/item-data.spec.ts
src/providers/item-data.ts

Fix returning items

---

src/pages/inventory/inventory.html
src/pages/inventory/inventory.ts

Fix add item button in inventory

---

.gitignore
config.xml

Update app version to 1.0.0

---

config.xml

Change bundle identifier

---

ionic.config.json
src/providers/api-url.ts

Change API url

---

config.xml

Update author tag in config.xml

---

src/pages/rental-details/rental-details.ts

290/Change rental itemID field to barcode

---

README.md

Change travis badge url

---

README.md

Update coveralls badge url

---

src/pages/rental-details/rental-details.html
src/pages/rental-details/rental-details.ts
src/test-data.ts

Add ability to store info on rentals

---

README.md

306/Add NSP badge

---

src/store/app/app.effects.spec.ts
src/store/app/app.effects.ts

Make status bar black on ios

---

src/store/items/items.effects.ts
src/store/kit-models/kit-models.effects.ts

Fix transformation of promises to observables

---

src/store/items/items.effects.spec.ts
src/store/items/items.effects.ts

Fix start rental condition

---

config.xml

Remove spinner during splash screen

---

src/pages/home/home.html
src/pages/kit-rental/kit-rental.html
src/pages/rental/rental.html

Remove ability to type barcodes on mobile

---

src/pages/add-kit-model/add-kit-model.html
src/pages/edit-item/edit-item.html

Closes #251 
This seemed to be an issue with ionic itself, but this workaround works and provides a similar experience than the intended original solution.

Use labels instead of inputs to avoid douple tap

---

src/pages/edit-kit/edit-kit.spec.ts
src/pages/edit-kit/edit-kit.ts

Prevent users from creating empty kits

---

src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts

Prevent users from making empty rentals

---

src/app/app.component.ts
src/app/app.html
src/app/app.spec.ts
src/pages/tabs/tabs.html
src/pages/tabs/tabs.ts

Move kits link from side menu to tab

---

.gitignore
.vscode/tasks.json
package.json

Add VS Code tasks

---

package-lock.json

Add npm 5 package lock

---

src/store/items/items.reducer.ts

Fix item showing up in inventory after being deleted

---

src/pages/edit-item/edit-item.spec.ts
src/pages/edit-item/edit-item.ts
src/pages/edit-kit/edit-kit.spec.ts
src/pages/edit-kit/edit-kit.ts

Add confirmation before deleting

---

src/mocks.ts
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts

Add items on desktop

---

src/constants.ts
src/providers/user-data.ts
src/utils/auth-http-helpers.ts

Add a version header to api requests

---

src/store/kit-models/kit-models.effects.ts
src/store/kit-models/kit-models.reducer.ts

Update store when updating kit models

---

src/pages/edit-kit/edit-kit.spec.ts
src/pages/edit-kit/edit-kit.ts

Fix editing kit name condition

---

config.xml

Bump app version to 1.1.0

---

package-lock.json
src/pages/add-kit-model/add-kit-model.html
src/pages/change-password/change-password.html
src/pages/edit-account/edit-account.html
src/pages/edit-item/edit-item.html
src/pages/edit-kit/edit-kit.html
src/pages/home/home.html
src/pages/inventory-filter/inventory-filter.html
src/pages/kit-rental/kit-rental.html
src/pages/login/login.html
src/pages/rental-details/rental-details.html
src/pages/rental/rental.html
src/pages/view-account/view-account.html

Closes #312 
Buttons are now moved to the bottom of the screen and stick if the content is too long to fit on one page for easier access.

Make buttons stick at bottom of screens

---

src/pages/add-kit-model/add-kit-model.html
src/pages/edit-item/edit-item.html

Do not hide model field when choosing brand

---

config.xml
package-lock.json
package.json
src/app/app.module.ts
src/constants.ts
src/mocks.ts
src/pages/login/login.html
src/pages/login/login.spec.ts
src/pages/login/login.ts
src/test.ts

Add link to website subscribe page

---

src/pages/inventory-filter/inventory-filter.html

Fix button styling in inventory filter modal

---

src/store/items/items.reducer.ts

New item with same barcode as deleted item uses cached data

---

src/pages/kits/kits.html

Add menu icon to kits tab

---

src/app/app.component.ts
src/app/app.html
src/app/app.spec.ts
src/pages/edit-item/edit-item.html
src/pages/view-item/view-item.html

Add confirmation that scan worked in add item

---

config.xml
src/models/items.ts
src/pages/inventory/inventory.html
src/pages/inventory/inventory.ts
src/services/items.service.spec.ts
src/services/items.service.ts
src/store/items/items.effects.spec.ts
src/store/items/items.effects.ts
src/store/items/items.reducer.ts

Fix infinite scroll in items

---

src/models/items.ts
src/pages/inventory/inventory.html
src/pages/inventory/inventory.ts
src/services/items.service.spec.ts
src/services/items.service.ts
src/store/items/items.reducer.ts

Show add new item button only on all

---

src/pages/add-kit-model/add-kit-model.html
src/pages/change-password/change-password.html
src/pages/edit-account/edit-account.html
src/pages/edit-item/edit-item.html
src/pages/edit-kit/edit-kit.html
src/pages/inventory/inventory.html
src/pages/kit-rental/kit-rental.html
src/pages/kits/kits.html
src/pages/login/login.html
src/pages/rental-details/rental-details.html
src/pages/rental/rental.html
src/pages/view-account/view-account.html

Remove padding on lists

---

src/mocks.ts
src/models/kit-models.ts
src/pages/add-kit-model/add-kit-model.html
src/pages/add-kit-model/add-kit-model.spec.ts
src/pages/add-kit-model/add-kit-model.ts
src/pages/edit-kit/edit-kit.html
src/pages/edit-kit/edit-kit.spec.ts
src/pages/edit-kit/edit-kit.ts
src/pages/kit-rental/kit-rental.html
src/pages/kit-rental/kit-rental.spec.ts
src/pages/kit-rental/kit-rental.ts
src/providers/kit-data.spec.ts
src/providers/kit-data.ts
src/store/items/items.effects.spec.ts
src/store/items/items.effects.ts
src/store/kit-models/kit-models.actions.spec.ts
src/store/kit-models/kit-models.actions.ts
src/store/kit-models/kit-models.effects.ts
src/store/kit-models/kit-models.reducer.ts
src/store/kits/kits.effects.spec.ts
src/store/kits/kits.effects.ts
src/test-data.ts
src/test.ts

Support multiple identical items in kits

---

src/constants.ts
src/store/items/items.effects.ts

Use new rent multiple items endpoint

---

src/pages/fields/fields.html
src/pages/fields/fields.ts

Display brand along with model in list

---

src/pages/rental-details/rental-details.spec.ts
src/pages/rental-details/rental-details.ts

Offset times to count for timezone

---

src/app/app.module.ts

Move tabs to bottom on android

---

src/store/items/items.effects.spec.ts
src/store/items/items.effects.ts

Show message when error on add to rental

---

src/constants.ts
src/mocks.ts
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts
src/store/items/items.actions.spec.ts
src/store/items/items.actions.ts
src/store/items/items.effects.spec.ts
src/store/items/items.effects.ts
src/test-data.ts

Check if item already exists when scanning

---

src/pages/rental-details/rental-details.spec.ts
src/pages/rental-details/rental-details.ts
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/test-data.ts
src/utils/date.ts
src/utils/index.ts

Send utc times to api

---

config.xml

417/Bump version to 1.4.2

---

src/pages/custom-field/custom-field.ts
src/pages/custom-fields/custom-fields.ts
src/pages/external-renters/external-renters.ts
src/pages/fields/fields.ts
src/pages/home/home.ts
src/pages/inventory-filter/inventory-filter.html
src/pages/inventory/inventory.ts
src/pages/kits/kits.ts
src/pages/rental-details/rental-details.ts
src/pages/rental/rental.ts
src/pipes/sort.pipe.ts
src/store/models/models.reducer.ts
src/utils/index.ts
src/utils/sort.ts

Sort filter options

---

src/constants.ts
src/pages/rental-details/rental-details.html
src/pages/rental-details/rental-details.spec.ts
src/pages/rental-details/rental-details.ts
src/providers/item-data.ts
src/store/items/items.actions.spec.ts
src/store/items/items.effects.ts
src/test-data.ts

Update to new rental endpoints

---

src/providers/custom-field-data.ts
src/providers/item-data.ts
src/providers/kit-data.ts

Switch to HttpClient query params

---

src/app/app.module.ts
src/interceptors/index.ts
src/interceptors/timeoutInterceptor.ts

Add timeout on network requests
