stockpile-co/app

.travis.yml
package.json

Resolve #8 
Simply added a few scripts to execute after a successful build on travis to transmit coverage info to coveralls and code climate.

Set up coveralls and code climate

---

ionic.config.json
src/theme/variables.scss

Added a few variables to get started on design, but there is still work to do. I also did not add environment variables, because there is [an open issue](https://github.com/driftyco/ionic-cli/issues/1205) to add it out of the box in ionic-scripts. If it isn't implemented by the time we need them, we can just use a custom implementation.
Close #3

App set up

---

ionic.config.json
karma.conf.js
package.json
src/app/app.component.ts
src/app/app.module.ts
src/app/app.spec.ts
src/extends-script.js
src/index.html
src/mocks.ts
src/providers/stockpile-data.spec.ts
src/providers/stockpile-data.ts
src/test.ts

Added support for HAL. `app.component.ts` makes a call to the api root to get the links.
I had to add an ugly script in `src/index.html` and `karma.conf.js` because the [ng-hal](https://github.com/dherges/ng-hal) module I use to construct the hal object does not work properly. Adding this script is the temporary fix. I opened an issue on the ng-hal repo, but the author does not have enough time to investigate the issue, so we will have to stick with this for now.
I also opened [an issue](https://github.com/emmanuelroussel/stockpile-app/issues/48) to add support for env variables to move the api link there.
Close #49

Add hal support

---

config.xml
package.json
src/app/app.component.ts
src/app/app.html
src/app/app.module.ts
src/app/app.spec.ts
src/constants.ts
src/mocks.ts
src/pages/home/home.html
src/pages/inventory/inventory.html
src/pages/item/item.ts
src/pages/login/login.spec.ts
src/pages/login/login.ts
src/pages/rental-details/rental-details.ts
src/pages/rental/rental.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts
src/providers/stockpile-data.spec.ts
src/providers/stockpile-data.ts
src/providers/user-data.spec.ts
src/providers/user-data.ts
src/test-data.ts
src/test.ts

Closes #15 
Login now sends the credentials to the api to authenticate. It stores the token in storage and the `angular2-jwt` library will automatically add it in the auth header for every request to the api. The call inside login uses `http` instead of angular2-jwt's `authHttp` because this is the only call where we don't want a header.
Every time a user opens the app, we verify if the token is expired. If not, we go to the TabsPage, if yes, we go to LoginPage.
I also added a logout button in a left side menu. Eventually, we might want to put some info about the user and organization in this menu.

Add authentication for organizations

---

src/pages/rental-details/rental-details.html
src/pages/rental-details/rental-details.ts

Closes #74 
I added today's date as the default value for start date and tomorrow's date as the default value for return date to avoid the picker to start at 01/01/2017. We'll have to check with our clients if those dates make sense.

Add datetime picker for dates

---

src/app/app.module.ts
src/constants.ts
src/mocks.ts
src/pages/item-filter/item-filter.html
src/pages/item-filter/item-filter.spec.ts
src/pages/item-filter/item-filter.ts
src/pages/item/item.html
src/pages/item/item.spec.ts
src/pages/item/item.ts
src/providers/inventory-data.ts
src/test-data.ts
src/test.ts

Closes #77
This PR is kinda of a mess. This is a very important UI functionality to have, but it was hard to implement. In order to make it adapt to all item properties (brand, model, status and category), I had to make some ugly code (inside `presentModal()`). I could not think of another way to use the same modal for all properties.
As we talked about, adopting a different strategy for items and brands, models and categories might help implementing a cleaner solution on the front end.
Code coverage also dropped drastically because of the difficulty to mock and test modals.
I welcome any suggestion on how to improve this.

Add ui to filter and add new item properties

---

src/pages/rental-details/rental-details.spec.ts
src/pages/rental-details/rental-details.ts

Closes #107 
Remove everything after the year, month and day in the date before making the call to the api to change the date to the format accepted by MySQL. Not the prettiest solution, but JavaScript's `Date` does not have any method to transform ISO 8601 dates to a format accepted by MySQL, so I had to do it by hand with `substring`.

Fix date format for rentals

---

src/pages/home/home.spec.ts
src/pages/home/home.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts
src/test-data.ts

Closes #115 
Replaced get status call by get item. Kept the original logic since it would be a bit complex to implement it for both rent/return and add/edit, but after add/edit get moved to the inventory view, I will be able to pass the whole item to the rent/return page which will prevent an identical call to get the item in each component.

Get status from item object

---

src/app/app.module.ts
src/constants.ts
src/mocks.ts
src/providers/api-url.spec.ts
src/providers/api-url.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts
src/providers/stockpile-data.spec.ts
src/providers/stockpile-data.ts
src/providers/user-data.spec.ts
src/providers/user-data.ts

This enables the returned API URL to change depending on the platform it
is running on.
Closes #134.

134/Change API URL constant to a service

---

src/mocks.ts
src/providers/api-url.spec.ts
src/providers/api-url.ts
src/providers/user-data.ts
src/test-data.ts

Closes #150 
We can use @AdamVig's previous implementation of testing for now since it is working and look if we need to refractor later. I also changed the platform condition from `core` to `cordova`. This will not work with PWAs as they do not have cordova, but still need the full url.

Fix transpile errors

---

src/pages/item/item.html

Closes #160 
I wasn't able to find a clean solution to make the whole fields in login clickable, but this seems to only be a problem on iOS.

Make whole field clickable

---

src/pages/item-filter/item-filter.html
src/pages/item-filter/item-filter.spec.ts
src/pages/item-filter/item-filter.ts

Closes #154
Here's what it looks like now:
The users can also still add new brands, models or categories like before.

Improve adding new brands, models, categories

---

src/pages/home/home.html
src/pages/home/home.spec.ts
src/pages/home/home.ts
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts
src/pages/item/item.spec.ts
src/pages/item/item.ts
src/pages/rental/rental.html
src/pages/rental/rental.spec.ts
src/pages/rental/rental.ts
src/pages/tabs/tabs.html
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts
src/test-data.ts

Closes #197, closes #186 and closes #161 
I also renamed the scan tab to "Rental". Not the greatest name, but without it, there is no indication of why you would want to scan items.
The scan button is also not shown on desktop anymore. It didn't make sense to show a feature that is not available. Typing barcodes is still available everywhere, but we'd have to check if it is necessary to keep it or not (if our client ever think to type barcodes instead of scanning them).
Here are a few screenshots of what it looks like:

Simplify typing barcodes

---

src/providers/user-data.ts

Closes #190 
This was way easier than I thought. Everything still works the same way it did since it is the same endpoints. The only element I had to change is the name of the property to get the userID in the token.

Add switch to user auth

---

src/pages/tabs/tabs.html

Closes #210 
Here's how it looks now:

Change icon of rental tab

---

README.md

Closes #223 
I wasn't able to rename the repo on Codebeat, so it will keep the old name. It seems to still function properly and creating a new project would remove all of the history.

Replace badges with new url

---

src/app/app.component.ts
src/app/app.html
src/app/app.module.ts
src/app/app.spec.ts
src/constants.ts
src/mocks.ts
src/pages/add-kit-item/add-kit-item.html
src/pages/add-kit-item/add-kit-item.spec.ts
src/pages/add-kit-item/add-kit-item.ts
src/pages/edit-kit/edit-kit.html
src/pages/edit-kit/edit-kit.spec.ts
src/pages/edit-kit/edit-kit.ts
src/pages/kits/kits.html
src/pages/kits/kits.spec.ts
src/pages/kits/kits.ts
src/pages/view-kit/view-kit.html
src/pages/view-kit/view-kit.spec.ts
src/pages/view-kit/view-kit.ts
src/providers/inventory-data.spec.ts
src/providers/inventory-data.ts
src/test-data.ts

Closes #240 
This simply adds the ability to manage kits. [This issue](#163) will add the ability to use them to rent items.
This caused quite a lot of code duplication/copy and pasting. I created [an issue](#237) to investigate potential solutions, but I feel like Angular's object oriented approach might not allow for the abstraction of page creation (which is where most of the code duplication happens with this PR).
Here are a few screenshots of what it looks like:

Add ability to manage kits

---

src/pages/rental-details/rental-details.ts

Closes #238 
There actually was only one place where an ID was declared as string, so changing it to number made more sense.

Change itemID type to number

---

src/app/app.scss
src/mocks.ts
src/pages/change-password/change-password.ts
src/pages/edit-account/edit-account.ts
src/pages/edit-item/edit-item.ts
src/pages/edit-kit/edit-kit.ts
src/pages/inventory/inventory.html
src/pages/inventory/inventory.ts
src/pages/kits/kits.html
src/pages/kits/kits.ts
src/pages/login/login.ts
src/pages/rental-details/rental-details.ts
src/pages/rental/rental.ts
src/test.ts

Closes #244 and closes #254 
Added loading inside an alert when doing an action that prevents the user from changing page (saving an item or kit, login in, renting/returning, etc.) and loading as a spinner within the page when the user can still interact with the app (viewing inventory or kits).

Add loading when waiting on the api

---

config.xml

Closes #282 
This automatically adds the value of NSCameraUsageDescription in Stockpile-Info.plist when running `ionic platform add ios`.

Fix missing info.plist key

---

src/app/app.module.ts
src/mocks.ts
src/pages/home/home.html
src/pages/home/home.spec.ts
src/pages/home/home.ts
src/pages/kit-rental/kit-rental.html
src/pages/kit-rental/kit-rental.spec.ts
src/pages/kit-rental/kit-rental.ts
src/pages/rental/rental.spec.ts
src/providers/kit-data.spec.ts
src/providers/kit-data.ts
src/test-data.ts

Closes #163 
This creates quite a bit of code duplication. The new kit rental page is similar to the regular rental page, but different enough that they cannot be combined into a single component. I will look into page creation abstraction in the near future.

Add ability to rent items by kit

---

src/pages/kit-rental/kit-rental.html
src/theme/variables.scss

Closes #311 
Grayed out the names items and added an icon when they need to be scanned.

Improve ux of renting kits

---

src/pages/login/login.html
src/store/app/app.effects.ts

Closes #354.
I'm not sure this is the right solution to this problem. It fixes the problem on the login screen, but it looks like this on the other screens:

Fix content going under statusbar

---

src/store/app/app.effects.ts

Closes #342 
It may seem dangerous to access the navs through an array, but when looking at the source code of [`getRootNav()`](https://github.com/ionic-team/ionic/blob/master/src/components/app/app.ts#L246) and [`getActiveNav()`](https://github.com/ionic-team/ionic/blob/master/src/components/app/app.ts#L211), it is also how it is done.

Fix deprecation warning about nav

---

src/app/app.module.ts
src/constants.ts
src/models/brands.ts
src/models/categories.ts
src/models/items.ts
src/models/kit-models.ts
src/models/kits.ts
src/models/models.ts
src/pages/add-kit-model/add-kit-model.ts
src/pages/edit-item/edit-item.ts
src/pages/fields/fields.html
src/pages/fields/fields.ts
src/pages/inventory/inventory.html
src/pages/inventory/inventory.ts
src/pages/kit-rental/kit-rental.ts
src/pages/kits/kits.html
src/pages/kits/kits.ts
src/pages/rental-details/rental-details.ts
src/pages/rental/rental.ts
src/pipes/index.ts
src/pipes/map-to-iterable.pipe.ts
src/pipes/sort.pipe.spec.ts
src/pipes/sort.pipe.ts
src/providers/api-url.ts
src/store/kit-models/kit-models.actions.ts
src/store/kit-models/kit-models.effects.ts
src/store/kit-models/kit-models.reducer.ts
src/test.ts
tsconfig.json

Closes #379 
Even though using a pipe for sorting [is not recommended by the Angular team](https://angular.io/guide/pipes#appendix-no-filterpipe-or-orderbypipe), I still decided to go that way. Because the data is provided from ngrx, it comes as a Map and is provided by an observable, so it cannot be sorted in place (unless the sorted array is stored in ngrx, but then we would run into complex code to keep that array up to date with changes. Which is the reason why we use maps instead of arrays in the first place).
So we will have to see if we run into performance issues while sorting big lists with a pipe. If not, this solution is much cleaner.

Sort results from api

---

src/pages/item/item.ts
src/pipes/map-to-iterable.pipe.ts
tsconfig.json

The app, when run on an Android emulator, wasn't recognizing the es2017 syntax (`Object.values` and `Object.entries`), so we have to revert to using ES2017 syntax.
This is a very easy fix and probably isn't worth spending too much time trying to figure out the compatibility issue between Ionic/Cordova and the TypeScript compiler.

Revert to using es2015 syntax

---

src/pages/inventory/inventory.html
src/pages/inventory/inventory.spec.ts
src/pages/inventory/inventory.ts
src/providers/item-data.ts
src/store/items/items.actions.spec.ts
src/store/items/items.actions.ts
src/store/items/items.effects.spec.ts
src/store/items/items.effects.ts
src/store/items/items.reducer.ts

Closes #370
Allows users to search in addition to the other filters (meaning that if they are currently filtering by brand, it will search among the items that have the selected brand and contain the search query i.e. applies the search filter in addition to the other filters when calling the api).

Add search bar in inventory

---

src/constants.ts
src/interceptors/errorInterceptor.ts
src/mocks.ts
src/providers/user-data.spec.ts
src/providers/user-data.ts
src/store/user/user.actions.spec.ts
src/store/user/user.actions.ts
src/store/user/user.effects.spec.ts
src/store/user/user.effects.ts

This is just some preliminary work on getting the action and effect set up to refresh access tokens.
The app still needs to dispatch the refresh token event when receiving `401`s from the api (unless the user is on the login page) and retry requests. This has been particularly challenging when dealing with multiple parallel requests, so merging this in will allow me to work on something else until I can figure out how a way to do it.
It shouldn't change any current behavior.

Add ability to refresh token

---

src/mocks.ts
src/models/custom-fields.ts
src/models/items.ts
src/pages/custom-field/custom-field.html
src/pages/custom-field/custom-field.spec.ts
src/pages/custom-field/custom-field.ts
src/pages/item/item.html
src/pages/item/item.spec.ts
src/pages/item/item.ts
src/store/items/items.effects.spec.ts
src/store/items/items.effects.ts
src/test-data.ts
src/test.ts

Closes #364 
I defaulted showing the timestamp to false when creating new custom fields. I feel like this should also be the case on the back end. Users will probably only want to show the timestamp for fields that change regularly, so there will probably be less of those. Making it false by default also makes sure it doesn't clutter the UI with unnecessary info if users forget to turn it off.
@AdamVig do you agree?

Add support to show timestamp for custom fields
